### ISSUE TITLE
event.nodeIds data type inconsistency

### ISSUE THREAD

**Issue by fedosejev** [ImperialCollegeLondon/PhyloCanvas#22]
When I listen to ```selected``` event, I get back ```event``` object with ```nodeIds``` property. If I select more than one node - ```nodeIds``` is an array. If I select just one node - ```nodeIds``` is a string.

To promote consistency, I think ```nodeIds``` should always be an array.

**Comment by jyothishnt** [comment]
Duplicate of #68
