### ISSUE TITLE
History and Navigational Improvements

### ISSUE THREAD

**Issue by richardgoater** [ImperialCollegeLondon/PhyloCanvas#35]
I feel the History tab needs a label to say "History", preferably vertically on the tab.
I also feel that a "Go back" button, not necessarily in the history panel itself, would be a welcome feature for navigating trees in a directory-style manner.

**Comment by richardgoater** [comment]
test for slack

**Comment by richardgoater** [comment]
test 2

**Comment by jyothishnt** [comment]
Added title to the history panel which goes vertical on close. Will be pushing it soon. :)

**Comment by richardgoater** [comment]
Closed by #37
