### ISSUE TITLE
Add Browserify support

### ISSUE THREAD

**Issue by fedosejev** [ImperialCollegeLondon/PhyloCanvas#36]
Would be great to use PhyloCanvas with Browserify.

**Comment by richardgoater** [comment]
I'm experimenting with building PhyloCanvas using Browserify on branch `refactore-grande`, but is your intention with this issue just for interoperability? Do the below lines do the trick?
https://github.com/ImperialCollegeLondon/PhyloCanvas/blob/refactore-grande/src/index.js#L2408-L2412
