### ISSUE TITLE
PhyloCanvas does not render tree within Bootstrap Tabs

### ISSUE THREAD

**Issue by joshsadam** [ImperialCollegeLondon/PhyloCanvas#52]
Hi.  I was speaking @daanensen about this issue yesterday and he said this was a known issue but asked me to create a ticket for it.  I also created a [plunker](http://plnkr.co/edit/L1nY4g23GzOCGV8hE28H?p=preview) recreating the issue.

**Comment by richardgoater** [comment]
Hi @joshsadam, thanks for raising this issue and for the plunker, which I had a quick look at. Please see the screenshot below:

![screen shot 2015-04-10 at 15 21 18](https://cloud.githubusercontent.com/assets/1429721/7090322/23e5ed44-df9a-11e4-86f5-b1150ffcafd0.png)

The debugger is paused just after your initialisation code, and the tree is rendered correctly on the left. It seems that the transclusion of the tab content causes something to go wrong with the PhyloCanvas instance. Would you agree that this indicates more of an Angular problem than a Bootstrap one?

One thing to try would be wrapping PhyloCanvas in its own directive and initialising it from within there, this should execute after the tab directives and may solve the problem. Do you think this sounds plausible?

**Comment by joshsadam** [comment]
That is a great idea, I will give it a try next week when I have some time and I will let you know how it goes.

**Comment by joshsadam** [comment]
Hi @richardgoater 

I updated the [plunker](http://plnkr.co/edit/L1nY4g23GzOCGV8hE28H?p=preview) using directive and included three scenarios: 

1. PhyloCanvas directive.
1. PhyloCanvas directive transcluded into a bootstrap panel.
1. PhyloCanvas directive with bootstrap tabs.

I do not believe this issue is not an issue of PhyloCanvas - sorry.  It appears that when angular-ui trancludes the generated svg something really strange happens to it, please see the plunker.  This also affects the history panel.  I found a good workaround using ui-router which will work for us.

If you see anything there that I am doing terribly wrong though, please let me know.

Thanks for your help.
Josh

**Comment by richardgoater** [comment]
Hi @joshsadam, I'm afraid I can't see the directive in the Plunker, is it the right link?

It's a shame that it isn't working and it could yet be a problem with PhyloCanvas. I think we'd like to ensure as much interoperability as possible so I would like to work this one out. 

Please continue to raise issues in the future if you find something isn't working.

**Comment by joshsadam** [comment]
Sorry I had it frozen on the previous version, you should be able to see it now.

**Comment by richardgoater** [comment]
Hi @joshsadam, I had a quick look at this again, the reason it breaks is because the element has dimensions of 0 when PhyloCanvas is initialised. I couldn't find a clean way to fix this but wrapping the initialisation in a `setTimeout` is a little hack to get it displaying correctly. Hope that helps :+1:
