### ISSUE TITLE
Mouse hit box for branch nodes should not be the same size as leaf nodes.

### ISSUE THREAD

**Issue by richardgoater** [ImperialCollegeLondon/PhyloCanvas#77]
See https://github.com/ImperialCollegeLondon/microreact/issues/120.

I'm suggesting a constant size of 5 pixels for branches, @fedosejev and @jyothishnt, please comment.

**Comment by jyothishnt** [comment]
I cant see ImperialCollegeLondon/microreact#120. :(

**Comment by fedosejev** [comment]
@jyothishnt:
![bug2](https://cloud.githubusercontent.com/assets/5831566/7368973/6ef0135a-eda5-11e4-9578-695bb0b9238a.gif)
